### ISSUE TITLE
Create field map entity types

### ISSUE THREAD

**Issue by levelos** [thinkshout/salesforce#1]
Field mapping entity type based on Entity API. Fields/props, at least:
- SF object type
- Drupal entity type
- A mapping of SF and Drupal fields
- Settings to determine when to sync data, E.g., create, update, delete.

Don't forget to lean on the work already done in the current module.

**Comment by kostajh** [comment]
When mapping fields, it would be helpful to have Drupal tell us if the Drupal field length and type matches the Salesforce field length and type.

Probably the most common error in Drupal/Salesforce integration is having an export fail due to field length in a Drupal field exceed what is allowed by Salesforce.

Additionally, an overview page (status report?) showing any problematic mappings where field length/type don't match would be useful.

**Comment by levelos** [comment]
Great ideas @kostajh, lets plan on it.

**Comment by levelos** [comment]
Closing this and moving @kostajh validation request into #10.
