### ISSUE TITLE
Make search filters functional

### ISSUE THREAD

**Issue by tauno** [thinkshout/salesforce#60]

**Comment by tauno** [comment]
The basic filters (entity type, id, SF id) are functional now: 74021ca

**Comment by tauno** [comment]
Need to add filter for last_sync date/time

**Comment by tauno** [comment]
Working - at least with date_popup enabled. Needs more testing without date_popup

**Comment by unclegcb** [comment]
Tested without date_popup, looks fine.

**Comment by unclegcb** [comment]
Filtering all seems to work well.
@tauno there's a "@TODO fix this options definition" listed for the "last sync action" filter. Any idea what the issue is with the options here? (I've added "created" which is what I'm doing with the initial revisions from hook_update_N)

(if the todo is irrelevant this can be closed)

**Comment by tauno** [comment]
I think we can close. The sync actions are hard coded for now. I think that's fine.
